swagger: '2.0'
info:
  version: '1.0'
  title: "Pigato_Luglio_SE2"
  description: Mondiali Russia 2018
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: pigato-luglio-se2.herokuapp.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /mondiali/teams:
    get:
      description: |
          Restituisce le informazioni relative alle squadre di calcio inserite che partecipano o hanno partecipato alla fase finale di Russia 2018
          
      operationId: view_teams
          
      responses:
        200:
          description: view all teams
          schema:
            type: string
            
  /mondiali/:nomesquadra/:still:
    post:
      description: |
          restituisce il JSON contenente un id assegnato alla squadra, il nome inserito e uno stato per capire se la squadra è ancora in gara
          
      operationId: insert_team
          
      responses:
        200:
          description: insert a team
          schema:
            type: string
            
            
  /mondiali/idSquadra/:id:
    get:
      description: |
          Restitusice un JSON contenente tutte le informazioni relative a quella squadra, dato il suo ID
          
      operationId: find_team_by_id
          
      responses:
        200:
          description: finds the info of a particular team given its id
          schema:
            type: string
            
  /mondiali/nomeSquadra/:name:
    get:
      description: |
          Restituisce un JSON contenente tutte le informazioni relative a quella squadra, dato il suo nome
          
      operationId: find_team_by_name
          
      responses:
        200:
          description: finds the info of a particular team given its name
          schema:
            type: string
  
  /mondiali/:id/:name/:is_still_in:
    put:
      description: |
          Aggiorna i dati di una determinata squadra
          
      operationId: update_teams_data
          
      responses:
        200:
          description: update the data of a particular team
          schema:
            type: string